// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgE6xG37Kd4c8URHvIgBPqjlOwCIOd04I',
    appId: '1:630008942712:web:c4d21782fefa728b67dd8d',
    messagingSenderId: '630008942712',
    projectId: 'flutter-practice-9b9e8',
    authDomain: 'flutter-practice-9b9e8.firebaseapp.com',
    storageBucket: 'flutter-practice-9b9e8.appspot.com',
    measurementId: 'G-SEP1GLNXFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYSaEmUm_CMdO5bn6kWUCsj6T1VHUjsWg',
    appId: '1:630008942712:android:0fd8affd6939019d67dd8d',
    messagingSenderId: '630008942712',
    projectId: 'flutter-practice-9b9e8',
    storageBucket: 'flutter-practice-9b9e8.appspot.com',
  );
}
